# ==============================================================================
# 1. RUTAS DE DIRECTORIOS LOCALES
# ==============================================================================
BACKUP_DIR="/home/a/Escritorio/Finalprueba/Backup"
GITLAB_HOME="/srv/gitlab"
#PASS_FILE="/home/a/Escritorio/FInalprueba/pass.txt"

# ==============================================================================
# 2. CONFIGURACIÓN DE RED (NAS / STORAGEBOX)
# ==============================================================================
RUTA_RED="//u488147.your-storagebox.de/backup"
USUARIO_RED="u488147"
# Usamos comillas simples para evitar conflictos con caracteres especiales
PASS_RED='ZZpower!24'
PUNTO_MONTAJE="/tmp/mnt_backup_red"

# ==============================================================================
# 3. CONFIGURACIÓN INTERNA DE GITLAB Y DOCKER
# ==============================================================================
EDITION="ce"
SERVICE_NAME="web"
CONFIG_DIR="$GITLAB_HOME/config"
LOGS_DIR="$GITLAB_HOME/logs"
DATA_DIR="$GITLAB_HOME/data"

# ==============================================================================
# 4. CONFIGURACIÓN SMTP (NOTIFICACIONES POR CORREO)
# ==============================================================================
SMTP_USER="no-reply@emisuite.es"
# Usamos comillas simples para la exclamación
SMTP_PASS='sncPOWER!25'
SMTP_FROM="no-reply@emisuite.es"
SMTP_TO="agabaldon@soincon.es"
SMTP_SERVER="smtp.office365.com"
SMTP_PORT=587
